# Generated by Django 2.2.3 on 2019-08-13 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plays', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemy',
            name='appear_field',
            field=models.IntegerField(default=0),
        ),
    ]
