# Generated by Django 2.2.3 on 2019-08-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plays', '0002_enemy_appear_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='time_spent',
            field=models.IntegerField(default=0),
        ),
    ]
