# Generated by Django 2.2.3 on 2019-08-13 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plays', '0003_player_time_spent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
    ]
