# Generated by Django 2.2.3 on 2019-08-14 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plays', '0004_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leveling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Level', models.IntegerField(default=0)),
                ('Xp_required', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='enemy',
            name='xp_gain',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='xp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='xp_level',
            field=models.IntegerField(default=0),
        ),
    ]
