# Generated by Django 2.2.3 on 2019-08-14 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plays', '0005_auto_20190815_0019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='xp_level',
            new_name='level',
        ),
    ]
